name: Next.js Staging CD

on:
  push:
    tags:
      - 's*'
    branches:
      - staging
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME }}:staging
            ${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }}
            NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}
            NEXT_PUBLIC_SHOW_RQ_DEVTOOLS=true

  deploy:
    name: Deploy on Hetzner VM
    runs-on: ubuntu-latest
    needs: [docker-image]
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env.local file for deploy
        run: |
          cat <<EOF > .env.local
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }}
          NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}
          EOF

      - name: Copy Docker Compose files
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml .env.local \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USER }}/app/

      - name: Build & Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          cd ~/app
          docker compose -p easeport_frontend_staging -f docker-compose.yml down
          docker compose pull
          docker compose -p easeport_frontend_staging -f docker-compose.yml up -d
          docker system prune -f
          EOF
